"""empty message

Revision ID: e9406b37f92e
Revises: 106a38cf1c9e
Create Date: 2022-08-27 11:23:26.360193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9406b37f92e'
down_revision = '106a38cf1c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('rating', sa.Integer(), nullable=False, server_default='0'))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'rating')
    # ### end Alembic commands ###
